# Generated by Django 5.0 on 2023-12-22 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveName', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn', models.DateField(auto_now_add=True)),
                ('timeOut', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectHandled', models.CharField(max_length=100)),
                ('dateStarted', models.DateField()),
                ('dateEnded', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryRange', models.CharField(max_length=100)),
                ('annualIncome', models.IntegerField()),
                ('taxable', models.IntegerField()),
                ('loans', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=255)),
                ('training', models.CharField(max_length=100)),
                ('projectReqt', models.CharField(max_length=100)),
                ('bond', models.IntegerField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('totalDays', models.CharField(max_length=10)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leaveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.leaves')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('employedDate', models.DateField()),
                ('deptId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_employees', to=settings.AUTH_USER_MODEL)),
                ('positionId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.position')),
            ],
        ),
    ]
