# Generated by Django 5.0 on 2023-12-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_employee_details_img_delete_empmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='deptId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='positionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.position'),
        ),
    ]
